In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,0,1],[0,1,0]])
y=a[b]
print(y)

[[[4 5 6]
  [1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
v=a*8
print(v)

[ 8 16 24]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
mask= (a%2==0)
print(mask)

[False  True False  True False]


In [ ]:
a=np.array([1,2,3])
y=[2*x for x in a]
print(y)



[np.int64(2), np.int64(4), np.int64(6)]


In [ ]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
b=np.array([7,8,9])
print(b.shape)
y=A*b
print(y)

(3,)
[[ 7 16 27]
 [28 40 54]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,0,1],[0,1,0]],dtype=bool)
a[b]

array([1, 3, 5])

In [ ]:
import numpy as np
a=np.array([0,1,2,3,4,5])
print(a.shape)
print(a)



(6,)
[0 1 2 3 4 5]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([10,20])
print(b.shape)
a+b

(2,)


array([[11, 22],
       [13, 24]])

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a[3:]=0
print(a)

[1 2 3 0 0 0]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
y=(a>2) & (a<6)
print(y)

[[False False  True]
 [ True  True False]]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
a[a>2]


array([3, 4, 5])

In [ ]:
import numpy as np
a=np.array([[1,2],[1,4],[5,6]])
a[a[:,1]>2]

array([[1, 4],
       [5, 6]])

In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
idx=np.array([4,0,4,1,2])
a[idx]

array([50, 10, 50, 20, 30])

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
mask=np.array([True,False,True,False,True,False])
a[mask]*10

array([10, 30, 50])

In [ ]:
import numpy as np
a=np.array([[1,5],[3,4],[5,6]])
a[a[:,0]%2==0,1]

array([], dtype=int64)

In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
mask=np.array([])