In [1]:
import numpy as np
value=np.array([1,2,3,4,5])
print(value)
print(type(value))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as pn
new=np.array(64)
print(new)

64


In [3]:
import numpy as np
val=np.array([[4,5,6],[6,7,8]])
print(val)

[[4 5 6]
 [6 7 8]]


In [4]:
import numpy as np
new=np.array(64)
value=np.array([1,2,3,4,5])
val=np.array([[4,5,6],[6,7,8]])

print(new.ndim)
print(value.ndim)
print(val.ndim)


0
1
2


In [5]:
import numpy as np

arr = np.array([[1,2,3,4]],)

print(arr)
print('number of dimensions :', arr.ndim)

[[1 2 3 4]]
number of dimensions : 2


In [6]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])


7


In [7]:
import numpy as np
arr=(1,2,3,4,5)

zeroes=np.zeros((3,4))
ones=np.ones((2,3))
range_arr=np.arange(0,10,2)
linspace=np.linspace(0,1,5)
identity=np.eye(3)
random_arr=np.random.rand(3,4)
er=np.random.randn(3,4)

print(random_arr)
print(er)
print(zeroes)
print(ones)
print(range_arr)
print(linspace)
print(identity)

[[0.02190941 0.14017384 0.84925985 0.72239854]
 [0.36033656 0.321958   0.93719986 0.64157986]
 [0.09191387 0.0436828  0.41140565 0.4215323 ]]
[[ 1.80207469 -0.49621397  2.16621725 -0.61092791]
 [ 0.3117436   0.6900698  -0.92244474 -0.83960047]
 [ 1.44680172 -1.17340085 -1.18052684  2.03704036]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
