In [ ]:
import numpy as np
arr=np.array((1))
print(arr)
print(arr.ndim)


1
0


In [ ]:
import numpy as np
a=np.array(34)
b=np.array((1,2,3,4))
c=np.array(((1,2,3,4),(6,7,8,9)))
d=np.array(((1,2,3),(4,5,6),(0,0,0)))
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(d)
print(b[2])


0
1
2
2
[[1 2 3]
 [4 5 6]
 [0 0 0]]
3


In [ ]:
import numpy as np
arr=[(10,2,6),(70,6,8)]
zeros=np.zeros((10,3))
ones=np.ones((3))
range_arr=np.arange(0,10,3)
linspace=np.linspace(20,100,10)
identity=np.eye(4)
random_arr=np.random.rand(3,4)
er=np.argmax(arr)
print(er)
means=np.mean(arr,axis=1)

print(zeros)
print(ones)
print(range_arr)
print(linspace)
print(identity)
print(random_arr)
print(means)

3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[0 3 6 9]
[ 20.          28.88888889  37.77777778  46.66666667  55.55555556
  64.44444444  73.33333333  82.22222222  91.11111111 100.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.1393076  0.30054253 0.87726148 0.82289628]
 [0.66891246 0.32419066 0.76394322 0.41423554]
 [0.46623878 0.49780831 0.30828285 0.20658032]]
[ 6. 28.]


In [ ]:
import numpy as np
arr=[(10,2,6),(70,6,8)]
zeros=np.zeros((10,3))
ones=np.ones((3))
range_arr=np.arange(0,10,3)
linspace=np.linspace(20,100,10)
identity=np.eye(4)
random_arr=np.random.rand(3,4)
er=np.argmax(arr)
print(er)
means=np.mean(arr,axis=1)

print(zeros)
print(ones)
print(range_arr)
print(linspace)
print(identity)
print(random_arr)
print(means)

crop yields array(tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

shape:(4, 5)
Data type:float64
total element:20
Number of dimensions:2

Total production:262.7tons
average per farm:[13.76 11.32 15.68 11.78]tons
average per season:[12.275 12.6   13.35  13.275 14.175]tons
maximum yield:16.8 tons
minimum yield:10.3tons

Best performingfarm:farm 3
	heir average yield:15.68tons


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)
print(np.sum(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))
print(np.max(a))
print(np.min(a))

(2, 3)
int64
6
2
21
[2.5 3.5 4.5]
[2. 5.]
6
1


In [ ]:
import numpy as np

# Assuming 'array' is a NumPy array or a list
# And 'total_sum' is intended to accumulate values

total_sum = 0 # Initialize sum
my_array = np.arange(100) # Example: create a NumPy array of 100 elements

for i in range(100):
    total_sum += my_array[i]

print(total_sum)

4950


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[10,11]])
print(B)
print(A.ndim)
print(B.ndim)
print(A.shape)
print(B.shape)
transpose=B.T
print(transpose)
inverse=np.linalg.inv(B)
print(inverse)
rank=np.linalg.matrix_rank(B)
print(rank)


[[ 5  6]
 [10 11]]
2
2
(2, 2)
(2, 2)
[[ 5 10]
 [ 6 11]]
[[-2.2  1.2]
 [ 2.  -1. ]]
2
