In [ ]:
import numpy as np
nutrient_needs=np.array([
     [120,60,80],
     [150,75,100],
     [100,50,70]
 ])
fertilizer_composition=np.array([
     [0.20,0.10,0.15],
     [0.15,0.20,0.10],
     [0.10,0.15,0.25]
])
print('nutrient requirements(kg/ha):')
print(nutrient_needs)
print('\nfertilizer composition(%):')
print(fertilizer_composition)

print('\ntransposed nutrients needs(nutrient*crops):')
print(nutrient_needs.T)

total_nutrients_per_crop=np.sum(nutrient_needs,axis=1)
print(f'\n total nutrients needed per crop:{total_nutrients_per_crop}kg/ha')

fertilizer_application=np.array([100,100,100])
nutrient_delivered=np.dot(fertilizer_application,fertilizer_composition)
print(f'\nnutrients from 100kg each fertilizer:{nutrient_delivered}')

det=np.linalg.det(fertilizer_composition)
print(f'\n determinant of fertilizer matrix;{det:.6f}')

scaling=np.eye(3)*1.1
enhanced_needs=np.dot(nutrient_needs,scaling)
print('\enhanced nutrient needs(10% increase):')
print(enhanced_needs)

nutrient requirements(kg/ha):
[[120  60  80]
 [150  75 100]
 [100  50  70]]

fertilizer composition(%):
[[0.2  0.1  0.15]
 [0.15 0.2  0.1 ]
 [0.1  0.15 0.25]]

transposed nutrients needs(nutrient*crops):
[[120 150 100]
 [ 60  75  50]
 [ 80 100  70]]

 total nutrients needed per crop:[260 325 220]kg/ha

nutrients from 100kg each fertilizer:[45. 45. 50.]

 determinant of fertilizer matrix;0.004625
\enhanced nutrient needs(10% increase):
[[132.   66.   88. ]
 [165.   82.5 110. ]
 [110.   55.   77. ]]


<>:32: SyntaxWarning: invalid escape sequence '\e'
<>:32: SyntaxWarning: invalid escape sequence '\e'
/tmp/ipykernel_2059/2092809830.py:32: SyntaxWarning: invalid escape sequence '\e'
  print('\enhanced nutrient needs(10% increase):')
